export const AUTH_ACTION = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  LOG_OUT: 'LOG_OUT',
};

export const APP_ACTION = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  REQUIRE_LOGIN_PAGE: 'REQUIRE_LOGIN_PAGE',
  UPDATE_POSITION: 'UPDATE_POSITION',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_ADDRESS_MODAL: 'OPEN_ADDRESS_MODAL',
  CLOSE_ADDRESS_MODAL: 'CLOSE_ADDRESS_MODAL',
  CHANGED_COUNTRY: 'CHANGED_COUNTRY',
  CHANGE_COUNTRY_SUCCESS: 'CHANGE_COUNTRY_SUCCESS',
  SET_APP_DATA: 'SET_APP_DATA',
  GET_CONFIGURATION_APP: 'GET_CONFIGURATION_APP',
  GET_CONFIGURATION_APP_SUCCESS: 'GET_CONFIGURATION_APP_SUCCESS',
  GET_CONFIGURATION_APP_FAIL: 'GET_CONFIGURATION_APP_FAIL',
  CLEAR_ERROR: 'CLEAR_ERROR',
  OPEN_FULL_MAP_VIEW: 'OPEN_FULL_MAP_VIEW',
  CLOSE_FULL_MAP_VIEW: 'CLOSE_FULL_MAP_VIEW',
  SAVE_PERMISSION_PHOTO: 'SAVE_PERMISSION_PHOTO',
};

export const LISTING_ACTION = {
  GET_LISTING_DATA: 'GET_LISTING_DATA',
  GET_LISTING_DATA_SUCCESS: 'GET_LISTING_DATA_SUCCESS',
  GET_LISTING_DATA_FAILURE: 'GET_LISTING_DATA_FAILURE',
};

export const NETWORK_ACTION = {
  SET_STATUS_CONNECTED: 'SET_STATUS_CONNECTED',
  SET_STATUS_CONNECTED_SUCCESS: 'SET_STATUS_CONNECTED_SUCCESS',
  SET_STATUS_CONNECTED_FAILURE: 'SET_STATUS_CONNECTED_FAILURE',
};
