export const AUTH_ACTION = {
  LOG_IN: 'LOG_IN',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  SET_LOGGED_IN_STATE: 'SET_LOGGED_IN_STATE',
};
